apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
spec:
  containers:
  - name: mycontainer
    image: ghcr.io/vadym-marchenko/telebot.git:v1.0.1-linux-arm64
    env:
      - name: API_SECRET
        valueFrom:
          secretKeyRef:
            name: mysecret1
            key: api_secret
  restartPolicy: Never