apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
spec:
  containers:
  - name: kbot-app
    image: ghcr.io/vadym-marchenko/telebot.git:v1.0.1-linux-arm64
    ports:
    - containerPort: 80
  - name: alpine-sidecar
    image: alpine:latest
    # This command keeps the sidecar container running. In a real-world scenario,
    # this could be a logging agent, a proxy, or another utility process.
    command: ["/bin/sh", "-c"]
    args: ["while true; do echo 'Sidecar is running'; sleep 30; done"]
