apiVersion: v1
kind: Secret
metadata:
  name: kbot-secret
type: Opaque
data:
  # The value for API_KEY must be base64 encoded.
  # Example: echo -n 'your-super-secret-api-key' | base64
  API_KEY: eW91ci1zdXBlci1zZWNyZXQtYXBpLWtleQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbot-secret-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kbot-secret-app
  template:
    metadata:
      labels:
        app: kbot-secret-app
    spec:
      containers:
      - name: kbot
        image: ghcr.io/vadym-marchenko/telebot.git:v1.0.1-linux-arm64
        ports:
        - containerPort: 80
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: kbot-secret
              key: API_KEY
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10