apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbot-ready
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kbot-ready
  template:
    metadata:
      labels:
        app: kbot-ready
    spec:
      containers:
      - name: kbot
        image: ghcr.io/vadym-marchenko/telebot.git:v1.0.1-linux-arm64
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10